import { makeStyles } from '@material-ui/core';
import * as colors from '../../uicontants';

const HomeStyles = makeStyles(() => ({
  root: {
    display: 'flex',
    flexDirection: 'row',
    height: '100%',
    width: '90%',
    marginLeft: '6%',
    marginTop: '2.5%',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pullFrame: {
    marginTop: 60,
  },
  button: {
    borderRadius: 10,
    // padding: '10px 20px 10px 20px',
    backgroundColor: colors.PRIMARY,
    color: colors.LIGHT_500,
  },
  overflow: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    '-webkit-line-clamp': 2,
    '-webkit-box-orient': 'vertical',
    textAlign: 'left',
  },
  overflowSingle: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    '-webkit-line-clamp': 1,
    '-webkit-box-orient': 'vertical',
    textAlign: 'left',
  },
  innerWrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  headerWrapper: {
    display: 'flex',
    width: '100%',
    // height: '100%',
    marginTop: '-2%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: colors.DARK_400,
  },
  shopWrapper: {
    display: 'flex',
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    padding: 20,
    justifyContent: 'center',
    backgroundColor: colors.LIGHT_100,
  },
  shopInnerWrapper: {
    display: 'flex',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  shopStatusBar: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTop: '1px solid #E3E4EB',
    borderBottom: '1px solid #E3E4EB',
    paddingTop: 15,
    paddingBottom: 15,
  },
  tags: {
    marginTop: 5,
    paddingLeft: 15,
    paddingTop: 2,
    paddingBottom: 2,
    paddingRight: 15,
    color: colors.LIGHT_100,
    borderRadius: 50,
  },
  chipButton: {
    backgroundColor: colors.DANGER_100,
    paddingLeft: 10,
    paddingTop: 2,
    paddingBottom: 2,
    paddingRight: 5,
    color: colors.PRIMARY,
    borderRadius: 50,
  },
  shopStatusAlign: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shopOfferWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    justifyContent: 'center',
    width: '100%',
    backgroundColor: colors.LIGHT_100,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    paddingBottom: 10,
  },
  categoryWrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    backgroundColor: colors.LIGHT_100,
    padding: 10,
    marginTop: 10,
  },
  categoryContainer: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'flex-start',
    // justifyContent: "space-evenly",
    marginTop: 10,
    flexWrap: 'wrap',
  },
  bannerWrapper: {
    padding: 10,
    // paddingBottom: 20,
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    marginTop: 10,
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: colors.LIGHT_100,
  },
  categoryChip: {
    display: 'flex',
    flexDirection: 'column',
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outletListWrapper: {
    borderRadius: 15,
    borderBottom: `1px solid ${colors.DARK_100}`,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  offerWrapper: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerInnerWrapper: {
    display: 'flex',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    border: `1px solid ${colors.LIGHT_500}`,
    borderRadius: 10,
    padding: 6,
    paddingLeft: 12,
    paddingTop: 12,
  },
  offerStyles: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginLeft: 10,
  },
  nftWrapper: {
    marginTop: 10
  }
}));

export default HomeStyles;
